### ISSUE TITLE
Build user interface to topic blog

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#115]
[Design doc](https://docs.google.com/document/d/1Egeqtnbwpw-wDOwAnOhEhatXaKUIdL2jvLFboHH_RMU/edit#)

**Comment by JeffAbrahamson** [comment]
Hey, thanks for the branch.  Some feedback, starting with the very procedural for when asking for feedback:

* think to rebase to master so that at least that noise isn't present
* clean up the branch first

Indeed, clean up branches regularly.  You'll improve your code by doing so.  You're already at 20 commits on something that I think is probably 4-5.  It would be more readable if you did that work first.

**Comment by JeffAbrahamson** [comment]
I'm pretty sure `MEDIA_ROOT` and (maybe) `MEDIA_URL` need to be set in `settings_local.py`.  Cf. #175 .

We don't yet support all those item types, best not to include them as options if they don't work yet...

It dies horribly if no images are chosen, but no image should be fine.  (We'll want to pick default images for some things, but in other places like a press release, just having no image is probably fine and normal.

After making several attempts at creating an item and being prompted to provide information I didn't have or (after a while) feel like making up, the entire form reset to empty.

**Comment by JeffAbrahamson** [comment]
* In `TopicBlogItemView`, try not to 500 if the get at line 52 fails. ;-)
* `TopicBlogItemEdit` should be protected with a `@login_required` decorator.  (Or maybe it's `@method_decorator(login_required)` on each method.)  Cf. [SO](https://stackoverflow.com/a/6069444/833300).
* My memory is bad: is `self.request.user` not already a User object? 
* Again, bad memory, but why do you need both `form_valid()` and `post()`?  In particular, I'm pretty sure that `post()` shouldn't call `super().form_valid()`.

**Comment by JeffAbrahamson** [comment]
Oh, also, for when we get so far as to permit already-uploaded-image browsing (e.g., white noise or something similar), we'll want to restrict by context.  So you'd not want to choose a twitter card image where a facebook image was uploaded, or a topic square when you need a header banner.

I don't think we can know yet what images formats we'll have, but we should surely plan to separate them somehow.

On that subject, I have no idea why I didn't write the image fields as `models.ImageField()`, but we surely should, no?

**Comment by Shriukan33** [comment]
> Hey, thanks for the branch. Some feedback, starting with the very procedural for when asking for feedback:
> 
>     * think to rebase to master so that at least that noise isn't present
> 
>     * clean up the branch first
> 
> 
> Indeed, clean up branches regularly. You'll improve your code by doing so. You're already at 20 commits on something that I think is probably 4-5. Some of the commits simply correct previous ones in the same branch. It would be more readable if you did that cleanup work first. (You might also find some of your bugs that way. ;-).
> 
> For example, I wanted to understand what model changes you'd made, because I saw a new migration. So I typed `git log 31f14a8..d18c743 topicblog/models.py` and saw eight commits. But `git diff 31f14a8..d18c743 topicblog/models.py` shows very nominal changes. So the git history wasn't being as informative as it might have been. (Related to that is the good practice of making regular dated snapshots of your development db so that you can easily rollback when you decide to abandon or change some branch that's got migrations in it. Or even so that you can simply work on another branch briefly and then come back to this one.)

Did rebase and reduced commit number :smile: 



> I'm pretty sure `MEDIA_ROOT` and (maybe) `MEDIA_URL` need to be set in `settings_local.py`. Cf. #175 .
> 
> We don't yet support all those item types, best not to include them as options if they don't work yet...
> 
> It dies horribly if no images are chosen, but no image should be fine. (We'll want to pick default images for some things, but in other places like a press release, just having no image is probably fine and normal.
> 
> After making several attempts at creating an item and being prompted to provide information I didn't have or (after a while) feel like making up, the entire form reset to empty. (I think it's because my image was invalid.)

The form didn't process because the ImageFields where mandatory (missing blank=True), I tested with two files and it displayed well. 
Can you elaborate on the last paragraph ? 
As for the settings, will move in commit 7b02bf4 the settings to local. 

>     * In `TopicBlogItemView`, try not to 500 if the get at line 52 fails. ;-)

It's in a try/except block, do you 500 ? Maybe it's like in Geoplan, an error that needs a specific except block. 

>     * `TopicBlogItemEdit` should be protected with a `@login_required` decorator.  (Or maybe it's `@method_decorator(login_required)` on each method.)  Cf. [SO](https://stackoverflow.com/a/6069444/833300).

Yes, I added that in the comments of the view already : https://github.com/transport-nantes/tn_web/blob/1bdcae7b3ebf33e41589f7aa02a9fe9617a8abd8/transport_nantes/topicblog/views.py#L75

>     * My memory is bad: is `self.request.user` not already a User object?
It's a string, if the user isn't authenticated, it's "AnonymousUser". otherwise it's the username ("benja" in my case, the SU) 

>     * Again, bad memory, but why do you need both `form_valid()` and `post()`?  In particular, I'm pretty sure that `post()` shouldn't call `super().form_valid()`.

super().form_valid just calls the default function, which is a redirect to succes URL really. 
In the case the form is valid on the .is_valid() method, we call our custom form_valid() method that creates the entry in DB. 
The return shouldn't call the form valid though. 
Maybe I'm wrong, is the call to form_valid implicit when the user POST on the URL ? 
I created the POST method to get the form and perform validation on it and handle the case where it's not valid. 
Is there another way to do that that you're aware of ?

**Comment by JeffAbrahamson** [comment]
Catching `BaseException` is way, way too broad.  You have almost no right to say what happened if that's what you catch.  Try catching something more specific.  You've read the [docs](https://docs.djangoproject.com/en/3.2/ref/exceptions/#database-exceptions) on what can be thrown?  And read the [source](https://github.com/django/django/blob/main/django/db/utils.py)?

(I think what's thrown for an unfound element is an `OperationalError`.)

**Comment by JeffAbrahamson** [comment]
`MEDIA_ROOT` needs to come from `settings_local`.

**Comment by JeffAbrahamson** [comment]
On `form_valid()`, what happens when you add scaffolding (log statements) to your code?  Where do you actually execute?

**Comment by Shriukan33** [comment]
> Catching `BaseException` is way, way too broad. You have almost no right to say what happened if that's what you catch. Try catching something more specific. You've read the [docs](https://docs.djangoproject.com/en/3.2/ref/exceptions/#database-exceptions) on what can be thrown? And read the [source](https://github.com/django/django/blob/main/django/db/utils.py)?
> 
> (I think what's thrown for an unfound element is an `OperationalError`.)

Fixed it in 24615bb
The ObjectDoesNotExist try/catch was enough, I then added a len check if the filter is empty.



> `MEDIA_ROOT` needs to come from `settings_local`.

Done in 7b02bf4018833883f369deb99f509a8a44493664




> On `form_valid()`, what happens when you add scaffolding (log statements) to your code? Where do you actually execute?

It called the super().form_valid twice, noticed that I didn't need to return or call anything in the self.form_valid function. 
So deleted it, now it saves the entry, and redirects to success URL with super.form_valid() 
Squashed that change into 84a9461

**Comment by JeffAbrahamson** [comment]
Looking good.

* slug is still required, should only be required at publication time though
* the image fields are still not nullable and they don't specify `upload_to` (which I _think_ we need, albeit different paths for different expected image sizes/purposes)
* In 3f5b0f4c, the comment should be "Add TopicBlog migrations" or something similar.  You're not performing a migration of the blog here.  Also,you don't fix image fields here.
* In 88108cc you have a double commit comment, which is confusing.  In addition, I don't see a reverse lookup being added in that commit.  I do see a `set_context()` function that has no code comment and isn't mentioned in the otherwise quite specific commit comment.
* In d539775 you do add a reverse lookup facility, but I'm unclear how it's different from the `app_name` at topicblog/urls.py:9.  Also, it's not a function.  Does it do anything?  I think `namespace` is for `include` not `path`.  Cf. [docs](https://docs.djangoproject.com/en/3.2/ref/urls/).
* In 524b630 what happens if you don't set the pk to be RO?  I've never seen an admin display permit pk editing.  What problem are you solving?
* c28ebc8 should be squashed away in your cleanup (at least the MEDIA part)
* In 84a9461 you still have `BaseException`.
* 49d6960 is highly specific to a private variable of your own `settings_local`, this isn't right
* c171556 - we should standarise on whether or not we have trailing '/'.  I'm not aware of an RFC specifying it, but the semantic difference seems quite real, and I'd suggest we standardise on without.  Cf. [SO](https://stackoverflow.com/questions/5948659/when-should-i-use-a-trailing-slash-in-my-url).  Also cf. [this](https://searchfacts.com/url-trailing-slash/) and [this](https://ahrefs.com/blog/trailing-slash/).
* In eaf58a2, I'm not convinced that "Bad slug" is a very user friendly error message (do users know this word?), even before fr != en.  Also in 557d093.

**Comment by Shriukan33** [comment]
Some of those are now outdated because the branch is cleaned but will answer to some : 

> Looking good.
> 
>     * slug is still required, should only be required at publication time though
Slug is no longer required to create an item, but surely a function to check that the item has a slug and is publishable will follow in the interface, it's a WIP but will come ! :smile: 

>     * the image fields are still not nullable and they don't specify `upload_to` (which I _think_ we need, albeit different paths for different expected image sizes/purposes)

Actually we don't need to specify the upload_to parameter unless we want the uploaded file to be saved somewhere else than the MEDIA ROOT directory now. 
ImageField now have blank=True. 

>     * In [d539775](https://github.com/transport-nantes/tn_web/commit/d53977545dcc7da90bd44aa11211b3bbd0de940e) you do add a reverse lookup facility, but I'm unclear how it's different from the `app_name` at topicblog/urls.py:9.  Also, it's not a function.  Does it do anything?  I think `namespace` is for `include` not `path`.  Cf. [docs](https://docs.djangoproject.com/en/3.2/ref/urls/).

The namespace is indeed for include, it allows me in the "get_absolute_URL" and "get_edit_URL" functions to use the reverse function to return proper URLs. Without the namespace specified, Django raises an error stating that "topicblog" is not a valid namespace. 
As for the function, I found that defining get_absolute_url() has the perk to allow you to have a button in the admin panel to see the item directly on the website (the button is invisible if the function is not explicitly defined) but more important, it allows me to use object.get_absolute_URL in the template that displays List of items (no PR yet but will come). You can access functions defined in models in templates basically. And I use it to retrieve the URL because I can't use reverse in templates. 



>     * In [524b630](https://github.com/transport-nantes/tn_web/commit/524b630ea7659a7ceec978acb10c8fcb955b3bfa) what happens if you don't set the pk to be RO?  I've never seen an admin display permit pk editing.  What problem are you solving?

Making the pk RO allows Django to display the value of the PK. 
By default in admin panels, Read Only are hidden, unless specified in the admin.py. 
So not making the PK read only would simply hide the PK field in admin panel. 

>     * [49d6960](https://github.com/transport-nantes/tn_web/commit/49d696084c880eaa315b2a43b81c1f21860ec7d8) is highly specific to a private variable of your own `settings_local`, this isn't right

True, I completely missed that. Any suggestion about how to make MEDIA ROOT not tracked ? 

>     * [c171556](https://github.com/transport-nantes/tn_web/commit/c17155672a4fb72a39acd3de89c7a61e095fd70a) - we should standarise on whether or not we have trailing '/'.  I'm not aware of an RFC specifying it, but the semantic difference seems quite real, and I'd suggest we standardise on without.  Cf. [SO](https://stackoverflow.com/questions/5948659/when-should-i-use-a-trailing-slash-in-my-url).  Also cf. [this](https://searchfacts.com/url-trailing-slash/) and [this](https://ahrefs.com/blog/trailing-slash/).

Can't remember the specific details about this, but basically it was construction an url with concatenated words where it should have been a trailing slash. 
Also your links suggest that trailing slashes are ok (I read it really quick, maybe missed details) 
Will get back on that issue when I'm going to make the PR about List View !

>     * In [eaf58a2](https://github.com/transport-nantes/tn_web/commit/eaf58a220b545dc680e5d22c3e6303912d5ceafe), I'm not convinced that "Bad slug" is a very user friendly error message (do users know this word?), even before fr != en.  Also in [557d093](https://github.com/transport-nantes/tn_web/commit/557d0936b6db29cfef9950fd419605a39995bb0e).

Translated, but the word slug has no french equivalent except itself that I am aware of : https://www.wordreference.com/enfr/slug
Open to suggestion to improve on that, I don't know better words for slug than slug. :disappointed:

**Comment by JeffAbrahamson** [comment]
@Shriukan33 Could you please scan this issue for anything you think needs to be done, make separate issues for those items, then close this one?  It's getting rather cumbersome.
